# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run

run-name: "Mute Alerts"

on:
   workflow_dispatch:
    inputs:
      start:
        description: "Start time of mute_alert"
        required: true
        type: string
      end:
        description: "End time of mute_alert"
        required: true
        type: string
      dc:
        description: "Name of DC"
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  call-alerts:
     uses: rakesh2525/Practice/.github/workflows/blank.yml@main
     with:
       start: ${{ github.event.inputs.start }}
       end: ${{ github.event.inputs.end }}
       dc: ${{ github.event.inputs.dc }}
